accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    #함수형뷰와 CBV의 차이 as_view사용
    # path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    # 특정유저의 pk가 필요
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    # root setting의 경로 추가 방법
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [

    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.auto_now_Add
from projectapp.models import Project


class Article(models.Model):
    #회원 탈퇴 했을때 게시글이 사라지지 않고 주인없음 느낌
    # related name 접근시 사용할 이름
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

accountapp/forms.py
# 수정시 id 못바꾸게

from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
# 장고에서 제공하는 user, 기본적으로 제공하는데 상속받아 재정의 해서 사용도 가능
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
# 장고에서 제공하는 cbv의 제너릭뷰
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from accountapp.models import HelloWorld
from articleapp.models import Article

has_ownership = [account_ownership_required, login_required]


@login_required
def hello_world(request):
    # 헤더에서 로그인했는지 안했는지 였는대 뷰에서도 똑같이 적용
    if request.user.is_authenticated:
        if request.method == "POST":
            # helloworld input 가져와
            temp = request.POST.get('hello_world_input')

            # helloworld의 새로운객체가 여기로 들어감
            new_hello_world = HelloWorld()
            # temp의 내용을 helloworld.text에 저장
            new_hello_world.text = temp
            # db에 데이터를 저장
            new_hello_world.save()
            # hello의 모든데이터ㅗ를 모두 긁어옴

            # 반복출력 이유는.. 항상 post들어오면 반복저장
            # post완료 이후엔 get로 돌아가게끔 만들어 줘야함
            # hello_world_list=HelloWorld.objects.all()
            # return render(request, 'accountapp/hello_world.html', context={'hello_world_list':hello_world_list})# context = data꾸러미
            # post끝나면 account앱에 hello_world 로 reverse하셈
            return HttpResponseRedirect(reverse('accountapp:hello_world'))
        else:
            hello_world_list = HelloWorld.objects.all()
            return render(request, 'accountapp/hello_world.html',
                          context={'hello_world_list': hello_world_list})  # context = data꾸러미
    # else:
    #     return HttpResponseRedirect(reverse('accountapp:login'))


###본강의

class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm  # 이것 또한 기본제공 확인핤것
    # 성공햇다면 어디로 보낼것인가
    # 클래스형에서는 lazy사용..
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/create.html'

    # def form_valid(self, form):
    #     temp_user = form.save(commit=False)
    #     temp_user.pk = self.request.user.pk
    #     temp_user.save()
    #     return super().form_valid(form)
    #
    # def get_success_url(self):
    #     return reverse('accountapp:login', kwargs={'pk': self.object.pk})


class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    # template에서 사용하는 유저 객체의 이름
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

    paginate_by = 25

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())

        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)


# 일반 함수에 사용하는 데코레이터를 메서드에 사용할수 있도록 변환해주는
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    # 성공햇다면 어디로 보낼것인가
    # 클래스형에서는 lazy사용..
    context_object_name = 'target_user'
    template_name = 'accountapp/update.html'

    # success_url = reverse_lazy('articleapp:list')
    def form_valid(self, form):
        temp_user = form.save(commit=False)
        temp_user.pk = self.request.user.pk
        temp_user.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('accountapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>SignUp</h4>
    </div>
        {#  view에 있는 routing으로 매핑  #}
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {#    view에서  form클래스 지정해준거(UserCreationForm 를 가지고 즉 html로 만들어줌  #}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="create">
        </form>
    </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Quit</h4>
    </div>
        {#  view에 있는 routing으로 매핑  #}
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {#    view에서  form클래스 지정해준거(UserCreationForm 를 가지고 즉 html로 만들어줌  #}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3" value="탈퇴">
        </form>
    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}


{% block content %}

    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
            {#            <p>#}
            {#                {{ target_user.date_joined }}#}
            {#            </p>#}



            {% if target_user.profile %}
                <img src="{{ target_user.profile.image.url }}" alt="" style="height: 12rem;
                     width: 12rem; border-radius: 20rem; margin-bottom: 2rem;">
                <h2 style="font-family: 'NanumSquareRoundOTFEB'">
                    {{ target_user.profile.nickname }}
                    {% if target_user == user %}
                        <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                            <span class="material-icons">
                                edit
                            </span>
                        </a>
                    {% endif %}
                </h2>
                <h5 style="margin-bottom: 3rem">
                    {{ target_user.profile.message }}
                </h5>
                {#            페이지 주인의 즉 지금 접속한유저와 같다면 아래의 링크를 보내줌 #}
            {% else %}
                {% if target_user == user %}
                    <a href="{% url 'profileapp:create' %}">
                        <h4 style="font-family: 'NanumSquareRoundOTFB'">
                            create profile
                        </h4>
                    </a>
                {% else %}
                    <h2>
                        닉네임이 없습니다.
                    </h2>
                {% endif %}
            {% endif %}



            {% if target_user == user %}
                <a href="{% url 'accountapp:update' pk=user.pk %}">
                    <span class="material-icons">
                                settings
                            </span>
                </a>
                <a href="{% url 'accountapp:delete' pk=user.pk %}">
                    <span class="material-icons">
                                cancel
                            </span>
                </a>
            {% endif %}
        </div>

        <div>
            {% include 'snippets/list_fragment.html' with article_list=object_list %}
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{% block content %}

    <div style="border-radius: 1rem; margin: 2rem; text-align: center;">
        <h1 style="font-family:'Nanum Brush Script', cursive; ">hello_world_LIST!</h1>

        <form action="/account/hello_world/" method="post">

            {% csrf_token %}
            <div>
                <input type="text" name="hello_world_input">
            </div>
            <div>
                <input type="submit" class="btn btn-primary" value="POST">
            </div>
        </form>

        {% if hello_world_list %}
            {% for hello_world in hello_world_list %}
            <h4>
                {{ hello_world.text }}
            </h4>
            {% endfor %}
        {% endif %}
    </div>




{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                {# login view에서 기본제공되는 form   #}
{#{{ form }} bootstrap 전용폼 사용#}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="눌러줘">
            </form>
        </div>


    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Change Info</h4>
    </div>
        {#  view에 있는 routing으로 매핑 요청보내는 url 해당 유저 pk #}
        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {% bootstrap_form form %}
            {#    view에서  form클래스 지정해준거(UserCreationForm 를 가지고 즉 html로 만들어줌  #}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3" value="update">
        </form>
    </div>

{% endblock %}