articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns= [


    path('list/',ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(template_name='articleapp/create.html'), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    # root setting의 경로 추가 방법
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.auto_now_Add
from projectapp.models import Project


class Article(models.Model):
    #회원 탈퇴 했을때 게시글이 사라지지 않고 주인없음 느낌
    # related name 접근시 사용할 이름
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)
    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

templates/snippets/card.html
<div>
    <img src="{{ article.image.url }}" alt="" style="object-fit: cover;">
</div>

templates/snippets/card_project.html
<div style="display: block;">
    <img src="{{ project.image.url }}" alt="">

    <h5 class="mt-2" style="font-family: 'NanumSquareRoundOTFR'; text-align: center">
        {{ project.title | truncatechars:6 }}
    </h5>
</div>

templates/snippets/list_fragment.html
{% load static %}



    <style>

        .container {
            padding: 0;
            margin:0;
        }

        .container a {
            width: 42%;
            max-width: 250px;
        }

        .container div {
            display: flex;
            justify-content: center;
            align-items: center;

            border-radius: 1rem;
        }

        .container img {
            width: 100%;
            border-radius: 1rem;
            height: auto;
            object-fit: cover;
        }

    </style>
    {% if article_list %}
        <div class="container">
            {% for article in article_list %}
                <a href="{% url 'articleapp:detail' pk=article.pk %}">
                    {#  for문으로 돌린 article이 스니펫에 있는 article로 넘겨줌   #}
                    {% include 'snippets/card.html' with article=article %}
                </a>
            {% endfor %}
        </div>
        <script src="{% static 'js/magicgrid.js' %}"></script>
    {% else %}
        <div style="text-align: center">
            <h1>No Articles yet!</h1>
        </div>
    {% endif %}

    {% include 'snippets/pagenation.html' with page_obj=page_obj %}
    <div style="text-align: center">
        <a href="{% url 'articleapp:create' %}" class="btn btn-dark
        rounded-pill px-3 mt-3 mb-3">
            Create Article
        </a>

    </div>

templates/snippets/pagenation.html
<div style="text-align: center; margin: 1rem 0;">
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}"
           class="btn btn-secondary rounded-pill">
            {{ page_obj.previous_page_number }}
        </a>
    {% endif %}
{#now page num#}
    <a href="?page={{ page_obj.number }}"
       class="btn btn-secondary rounded-pill active">
        {{ page_obj.number }}
    </a>
{#if next page 가 있으면#}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}"
           class="btn btn-secodary rounded-pill">
            {{ page_obj.next_page_number }}
        </a>
    {% endif %}
</div>