accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    #함수형뷰와 CBV의 차이 as_view사용
    # path('hello_world/', hello_world, name='hello_world'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),
    # 특정유저의 pk가 필요
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns= [


    path('list/',ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(template_name='articleapp/create.html'), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('', ArticleListView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    # root setting의 경로 추가 방법
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'

urlpatterns= [

    path('list/', ProjectListView.as_view(), name='list'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns= [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),

]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
{#start of head#}
{% include 'head.html' %}

{#end of head#}

<body style="font-family: 'NanumSquareRoundOTFEB';">

{#start of header#}
{% include 'header.html' %}
{#end of header#}
<hr>
{% block content %}
{% endblock %}
<hr>
{#start of footer#}
{% include 'footer.html' %}
{#end of footer#}

</body>

</html>

templates/footer.html
<footer>

    <div class="pragmatic_footer">
        <div class="pragmatic_footer_button">
            <span>공지사항 |</span>
            <span>제휴문의 |</span>
            <span>서비스소개</span>
        </div>
        <div style="margin-top: 1rem">
            <h6 class="pragmatic_logo">Pinterest Proj</h6>
        </div>

    </div>

</footer>

templates/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
{#    mobile#}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pragmatic</title>
    {#  bootstrap  #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          crossorigin="anonymous">
    {#google fonts#}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Brush+Script&display=swap" rel="stylesheet">

    {#    default css link #}
    <link rel="stylesheet" tabindex="text/css" href="{% static 'base.css' %}">


    {#    fonts#}
    <style>

        @font-face {
            font-family: 'NanumSquareRoundOTFB';
            src: local('NanumSquareRoundOTFB'),
            url("{% static 'fonts/NanumSquareRoundOTFB.otf' %}") format("opentype");
        }

        @font-face {
            font-family: 'NanumSquareRoundOTFEB';
            src: local('NanumSquareRoundOTFEB'),
            url("{% static 'fonts/NanumSquareRoundOTFEB.otf' %}") format("opentype");
        }

        @font-face {
            font-family: 'NanumSquareRoundOTFL';
            src: local('NanumSquareRoundOTFL'),
            url("{% static 'fonts/NanumSquareRoundOTFL.otf' %}") format("opentype");
        }

        @font-face {
            font-family: 'NanumSquareRoundOTFR';
            src: local('NanumSquareRoundOTFR'),
            url("{% static 'fonts/NanumSquareRoundOTFR.otf' %}") format("opentype");
        }
    {#    icon    #}
    </style>
        <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">
</head>

templates/header.html
<header>
    <div class="pragmatic_header" style="text-align: center; margin: 2rem 0;">
        <div>
            <h1 class="pragmatic_logo">Pinterest Proj</h1>
        </div>
        <div class="pragmatic_header_navbar">
            <a href="{% url 'articleapp:list' %}" class="pragmatic_header_nav">
                <span>Articles</span>
            </a>
            <a href="{% url 'projectapp:list' %}" class="pragmatic_header_nav">
                <span>Projects</span>
            </a>
            <a href="{% url 'subscribeapp:list' %}" class="pragmatic_header_nav">
                <span>Subscriptions</span>
            </a>
            {#            <span>nav1</span>#}
            {% if not user.is_authenticated %}
                {#          내가 만든 홈페이지 어느에서든지 로그인을 하면 해당 url을 next인자로 넘겨주고 로그인을 하고나서 원래있는 자리로 돌아옴  #}
                <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="pragmatic_header_nav">
                    <span>login</span>
                </a>
                <a href="{% url 'accountapp:create' %}?next={{ request.path }}" class="pragmatic_header_nav">
                    <span>SingUp</span>
                </a>
            {% else %}
                <a href="{% url 'accountapp:detail' pk=user.pk %}" class="pragmatic_header_nav">
                    <span>MyPage</span>
                </a>
                <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="pragmatic_header_nav">
                    <span>logout</span>
                </a>
            {% endif %}
        </div>
    </div>

</header>